name: Deploy to Azure Web App - CSE486

on:
  push:
    branches:
      - pipeline-draft
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      #ENTRA STUFF
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENTID }}
          tenant-id: ${{ secrets.TENANTID }}
          subscription-id: ${{ secrets.SUBSCRIPTIONID }}



      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "CSE486"
          package: .
